BLSQ/iaso

hat/assets/js/apps/Iaso/domains/forms/messages.js, hat/assets/js/apps/Iaso/domains/links/components/LinksCompareComponent.js, hat/assets/js/apps/Iaso/domains/links/components/LinksValueComponent.js, iaso/api/data_sources.py
- Fixed the datasource API endpoint response. Versions attribute shouldn't be an array of arrays
- Added a button to link to orgUnit details
- Listed the parents orgUnits of the current mapping link
=> Added link to the matching org units and a listed the OU link parents

plugins/polio/js/src/components/Inputs/OrgUnitsSelect.js, plugins/polio/js/src/hooks/useGetOrgUnits.js
- Not being able to create a campaign without any org units selected
- Fixed create campaign modal with validation errors on an empty state
- Fixed empty value warnings for org units component
=> Fix org units component when creating a new campaign

plugins/polio/js/src/components/Dashboard.js
- see https://bluesquare.slack.com/archives/C0214A5BR2L/p1622439729001600
- `district_count` and `budget_submitted_at` fields
=> [POLIO] Add fields to budget step

docker-compose.yml, runiasodev.sh
In the .env.dev example file there is a settings RDS_DB_NAME to set which env Database to use,  but it was not actually respected by runiasodev.sh or docker-compose.
=> Fix Allow setting which DB to use via the .env file

.docker/webpack/Dockerfile
deactivate it temporarly till we fix it
Step 7/11 : RUN npm ci
---> Running in eaf4498c5557
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/BLSQ/bluesquare-components.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
=> bluesquare-components install fail with npm-ci

.dockerignore
We were adding the node_modules of Polio and other useless stuff in the image.
=> Reduce the size of Iaso docker images

plugins/polio/api.py, plugins/polio/tests.py
- Ony show campaigns for a user's org unit or a descendant of the org unit that is assigned in his profile
---
Closes https://bluesquare.atlassian.net/browse/IA-569
=> Limit the list of campaigns visible to an user to the org units that are under his responsability

plugins/polio/js/src/components/Inputs/OrgUnitsSelect.js
- Org unit select box not showing when creating a new campaign
---
@madewulf If a user has an org unit configured on his profile, the org units select box won't show up when creating a new campaign. This is however not a complete fix to the issue, since a user can have multiple org units configured we need a method to figure out which is the parent org unit we need here.
=> Fixes not showing org unit select box when creating a new campaign

hat/settings.py, plugins/polio/api.py, plugins/polio/js/src/components/Dashboard.js, plugins/polio/tests.py, requirements.txt
- Use Django reset framework recommended implementation of filters and pagination
--- 
Separate this improvement in a different pull request but this is needed for the search query of the campaigns.
=> Improve pagination and fields ordering implementation

hat/settings.py
logger in iaso and beanstalk_worker were not using the correct format
(not printing date and module name) nor did they use the log level.
We now use this format for all modules. and correcty use the log level
env var.
Logging file in production didn't print the date (or use the formatting),
this is now corrected.
Note that at the moment there is no logger under `hat`
=> Fix log format issue, add formating to log file

hat/settings.py
integrate with Django to upload a bit more info to help debug
default_pii (personally identifiable information) include username and user's email
of course there is the probability as before that user info get included
in the trace
see https://sentry.io/security/
=> Enable Sentry integration for Django

requirements.txt
we had a somewhat outdated sentry version that poped warning in their web console
can't really test much locally but read their release note and it should be ok
=> Update to latest sentry-sdk version

.github/workflows/deploy.yml, .github/workflows/main.yml
Add a message when a deployment start.
That's about as little as spammy as I could make it without forking the Github action we are using
Ignore the color of the bar below, it's red
=> Reduce the size of the slack message

iaso/api/org_units.py, iaso/test.py, iaso/tests/api/test_orgunits.py
This PR does properly what I had to revert  this afternoon because it broke stuff. And add a ton of tests does make sure it doesn't break again.
=> Properly set warning in API when we try to set a group from another data source version on an org unit

.github/workflows/main.yml
This should ensure we don't have  once again migration missing in the main branch
=> CI Verify is there is no missing migration

hat/assets/js/apps/Iaso/domains/forms/config.js
- in `/dashboard/forms/list`'s table, "name" and "formId" fields are now aligned left
=> IA439 fix: align name and formId left

hat/assets/js/apps/Iaso/domains/orgUnits/config.js, hat/assets/js/apps/Iaso/domains/orgUnits/index.js, hat/assets/js/apps/Iaso/domains/orgUnits/utils.js
- Add color codes for Org Unit status: New = blue, validated = green, rejected=red
- green and red are the same colors as the `SnackBar`s
- blue is taken from `$primary-color` in  `_iaso.scss`
=> IA458 feat use color code for orgUnit statuses

plugins/polio/js/src/components/Dashboard.js
- Scope tab with map widget
- Add spinner component when shapes are still fetching
- Map widget from risk assessment tab
=> [IA-662] Move the map widget to its own tab / Add loader to map widget

plugins/polio/js/src/hooks/useGetRegionGeoJson.js
- Setting [refetchOnWindowFocus](https://react-query.tanstack.com/guides/window-focus-refetching) to false to prevent selected shapes from disappearing after switching tabs on the browser.
Please notice that as I wasn't able to reproduce this bug locally I couldn't test if this solution is solving the problem.
=> IA-652: Prevent refresh window focus

iaso/models/org_unit.py, plugins/polio/js/src/components/Dashboard.js, plugins/polio/js/src/components/MapComponent/MapComponent.jsx
- added a switch button to toggle selection mode when clicking org unit on map
- The user can either select/unselect an org unit, or all org units of the parent region
- When switching to region select, if org units of the region are already selected, clicking on an org unit of the region will select the remaining ones
- If all org units of a given region are selected, clicking on any org unit of that region will unselect the whole region.
- modified API to receive parent_id
Uploading Screen Recording 2021-07-20 at 14.04.22.mov…
- the switch button label text is hard coded as I couldn't get react-intl to work
- there is inline styling for the switch button, as using className with classes from useStyles didn't seem to work either
=> IA665 enable region selection

plugins/polio/js/src/components/Dashboard.js, plugins/polio/js/src/utils/convertEmptyStringToNull.js
- added `convertEmptyStringsToNull` in /utils
- converting all empty strings to null before passing `values` to `saveCampaign`. All fields that could have a value of `""` are marked as nullable in yup schemas, so this conversion seems safe.
=> IA662 fix: pass null to API when date empty

plugins/polio/models.py
we don't remove the history in case the removal or edition was by error, we just don't show it in the API anymore (in last_surge and last_reparedness)
=> IA-606 Allow to delete preparedness and surge data for a given campaign

hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js
trying to select a default source in `DataSourcesDialogComponent` would cause the component to crash as it was expecting a string and received a number
=> Hotfix: change dropdown label type to string

hat/assets/js/apps/Iaso/components/Cells/DateTimeCell.js, hat/assets/js/apps/Iaso/components/Cells/YesNoCell.js, hat/assets/js/apps/Iaso/domains/dataSources/config.js, hat/assets/js/apps/Iaso/domains/dataSources/messages.js, hat/assets/js/apps/Iaso/domains/devices/config.js, hat/assets/js/apps/Iaso/domains/forms/config.js, hat/assets/js/apps/Iaso/domains/forms/configArchived.js, hat/assets/js/apps/Iaso/domains/links/config.js, hat/assets/js/apps/Iaso/domains/mappings/config.js, hat/assets/js/apps/Iaso/domains/orgUnits/config.js, hat/assets/js/apps/Iaso/domains/orgUnits/groups/config.js, hat/assets/js/apps/Iaso/domains/orgUnits/types/config.js, hat/assets/js/apps/Iaso/domains/orgUnits/types/config.spec.js, hat/assets/js/apps/Iaso/domains/pages/index.js, hat/assets/js/apps/Iaso/domains/projects/config.js, hat/assets/js/apps/Iaso/domains/tasks/config.js, hat/assets/js/apps/Iaso/domains/users/config.js, plugins/polio/js/src/components/Dashboard.js, plugins/test/js/columns.js
PR on top of Christophe PR to make each column a bit more the same
- Use `settings.value` to access the value in Cell:
- Use `accessor` function and set an `id` field if we just want a different field *
- Remove useless <span> <section> etc.. in cell
- Remove Cell: when it's simple text we want displayed
- Added a standardised DateTimeCell which handle formatting to display `created_at` `updated_at` etc...
- - Added a standardised YesNoCell for boolean value
- fix some bug of columns marked sortable but which were not and crashed
- fix IA-739 sorting in  the project table
this PR also remove most textPlaceholder (the `--` that get displayed when there is no data) usage was inconsistant, tell me if you prefer with it and I will add it back everywhere.
The general idea is that `id` is the …
=> Mod: standardise table columns a bit

hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.js, hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.spec.js, hat/assets/js/apps/Iaso/domains/forms/detail.js
- When editing a form the value for single_per_period is now used
@olethanh , @beygorghor : no need for a double review, whoever has time first
https://user-images.githubusercontent.com/38907762/132011744-3c2e7280-03c6-4542-baa8-d7ae5f759c89.mov
=> Fix: display single_per_period's value if exists

hat/assets/js/apps/Iaso/domains/app/translations/en.json, hat/assets/js/apps/Iaso/domains/app/translations/fr.json, hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsLocation.js, hat/assets/js/apps/Iaso/domains/instances/messages.js, hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitSourceRefDisplay.js
- added placeholder message when OU type is null
- added textPlaceholder when soiurce reference is null
- added related translations
https://iaso-staging.bluesquare.org/dashboard/instance/instanceId/9427
=> patch: instanceDetails crash when null OrgUnitType

hat/assets/js/apps/Iaso/domains/links/config.js, iaso/api/instances.py
was caused because the status annotation is done in for_filters
=> fix crash when ordering instance by status

hat/assets/js/apps/Iaso/components/tables/SingleTable.js, hat/assets/js/apps/Iaso/domains/orgUnits/details.js
New component table has a useMemo to avoid multiple rerender.
Due to the fact that children table is loaded at the beginning and hidden, while changing tab, the table doesn't update his props and on the redirect is still passing old tab param value.
You have now a new props `propsToWatch` in `SingleTable`.
https://user-images.githubusercontent.com/12494624/132836022-0869c86e-8f8c-435e-98b4-ac88043026d3.mov
=> IA763: When sorting children of orgunit it switch tab

hat/assets/js/apps/Iaso/components/logs/LogsComponent.js, hat/assets/js/apps/Iaso/domains/orgUnits/config.js
- replaced `DateTimeCell` with `DateTimeCellRfc` in `/hat/assets/js/apps/Iaso/domain/orgUnits/config.js`'s `orgUnitsLogsColumns`
- removed some unused vars
issue https://bluesquare.atlassian.net/browse/IA-762?atlOrigin=eyJpIjoiYmUzMTgyZGQ5NmUxNDBkN2EyOWRiNWU4OTY4ZTU3NDIiLCJwIjoiaiJ9 should fix the issue back-end side
=> IA-780 patch dates displayed

hat/assets/js/apps/Iaso/constants/filters.js
while waiting for the overhaul of the search view, it should make the life of people in pbf/hfre easier
=> Orgunit Search: display version number for group

hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewPicker.js
https://user-images.githubusercontent.com/82500/133590676-283e6e71-60ef-4b41-9940-0a73cfab6720.mp4
add an OrgUnit button to open the dialog.
this is just a suggestion. Because it also mean there is two buttons which change the dyamic a bit?
=> OrgUnit Treeview, remove clear button if no selection

hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgunitsMapComponent.js, hat/assets/js/apps/Iaso/utils/index.js
- Added a timeout in `OrgunitsMapComponent` to avoid the map staying grey when navigating back and forth from list to map tab
- Added the `waitFor` function in utils
- duplicated the `fitToBound` related logic from `componentDidUpdate` into `componentDidMount` with the `checkFitToBound` method
=> IA-784 patch dispay orgunit map when switching tab

hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/OrgUnitMapComponent.js, package-lock.json
- Map will fit to bounds when navigation from OrgUnits search to `OrgUnitMap` by using the tables's action button
- Updated bluesquare-components to enable holding `Shift` to keep options list open in multiselect `Select` input
https://user-images.githubusercontent.com/38907762/134336637-ccd6fef5-2ad0-44e3-a0a8-2754276161a8.mov
=> IA-783 & IA-801

hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/TruncatedTreeview.js
- `TruncatedTreeview`will not trigger its `onClick` if left mouse button is held more than 150 ms
https://user-images.githubusercontent.com/38907762/134660945-1e18f47a-9736-4467-ada0-bfbaac7dc5ee.mov
=> IA-611 enable selection and copy in TruncatedTreeview

hat/assets/js/apps/Iaso/domains/instances/utils.js
According to [this](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group), this is fixing the problem, but is the behaviour still correct ?
=> SAFARI crash: fix regex

iaso/diffing/differ.py
slow down were caused by the new feature to show parent name.
We now prefetch related them.
on a Play.dhis2 source  the number of database goes down from 7200 to 23
and the diff is done in a few secs
=> ExportDHIS2Diff optimize diff

iaso/api/forms.py, iaso/tests/api/test_mobileforms.py, iaso/urls.py
- added route to urls.py
- sub-classed `MobileFormViewSet` from `FormViewSet` and filtered out forms with no version
- added tests for new mobile endpoint
Co-authored-by: Olivier Le Thanh Duong <olivier@lethanh.be>
=> IA-403: add mobile endpoint for forms+tests

iaso/api/form_versions.py, iaso/odk/parsing.py
- raise a `ValidationError` exception when `pyxform.Survey.to_xml` fails
- No changes on the front-end as the error is displayed and available for copy in the snackbar as with other API errors
It's a very basic change, I'm open for improvements
https://user-images.githubusercontent.com/38907762/141807711-ca81c350-1ba2-4532-9c50-c2f0a0ff8b32.mov
=> IA-873: return 400 for badly formatted xls

hat/assets/js/apps/Iaso/constants/menu.js, hat/assets/js/apps/Iaso/constants/routes.js, hat/assets/js/apps/Iaso/domains/forms/config.js, hat/assets/js/apps/Iaso/domains/forms/config.spec.js, hat/assets/js/apps/Iaso/domains/forms/configArchived.js, hat/assets/js/apps/Iaso/domains/forms/index.js, hat/assets/js/apps/Iaso/domains/forms/index.spec.js, hat/assets/js/apps/Iaso/domains/instances/constants.js, hat/assets/js/apps/Iaso/domains/orgUnits/details.js, hat/assets/js/apps/Iaso/domains/users/components/ProtectedRoute.js, hat/assets/js/apps/Iaso/domains/users/utils.js, hat/assets/js/apps/Iaso/index.js, hat/assets/js/test/utils.js, iaso/api/form_versions.py, iaso/api/forms.py, plugins/polio/js/config.js
- changed "permission" field to "permissions" in `menuItems`. It now takes an array i.o a string
- gave access to Forms to "iaso_submissions" permission
- updated `ProtectedRoutes` to check for an array of permissions i.o single one
- users with `iaso_submissions` permission can view `/forms/list`, but write actions are not available
- id. for ArchivedForms: the actions column is removed
https://user-images.githubusercontent.com/38907762/140543052-6c7570ce-3355-4995-b42e-6ab17af2bd1c.mov
=> IA-885 & IA-901 restrict actions submissions perm

iaso/api/groups.py
Prefetch related queries
and only return necessary data. Previously we were returning the DataSource and all the versions with no relation to the group
This diminish the response size, the returned json is now 36k from
216.25kb before.
And the number of SQL queries on my local database goes from 1300 to 7.
Request Reponse time have been improved from 4622 ms (4 seconds) to
831ms.
=> IA-994 Speed up the group filter selector

plugins/polio/api.py, plugins/polio/management/commands/weekly_email.py
Now that we have deep linking for campaign in creation email and update email, directly link to the concerned campaign
instead of the campaign page.
=> POLIO-118 Direct Link Campaign in email

plugins/polio/api.py, plugins/polio/js/src/pages/LQAS/utils.ts
- Added null check on `round_1.started_at` in `findCampaigns` method
- get updated config files from 1Password
- update lqas-config and im-config in django admin
- check that the country ids match those in your local DB
- To display results, match the districts not found using org unit aliases
=> POLIO-165: Hotfix add senegal to lqas im

plugins/polio/js/src/components/LQAS-IM/ImSummary.tsx, plugins/polio/js/src/components/LQAS-IM/LqasSummary.tsx, plugins/polio/js/src/utils/LqasIm.tsx
- Removed condition preventing calculation of vaccinated % for `ImSummary` for Global IM
- removed text-shadow and used darker color for text with status `warning`in `LqasSummary`and `ImSummary
=> POLIO-166: add % to globalIM, remove txt shadow

hat/assets/js/apps/Iaso/domains/instances/components/CreateReAssignDialogComponent.js, hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.js, hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewPicker.js
- fix `fieldValue.orgUnit.value !== undefined` not working if === null
- make the org unit field required
- remove clearable button as not mandatory her
e
=> IA-1008 submission creation

plugins/polio/js/src/pages/IM/index.js, plugins/polio/js/src/pages/LQAS/index.js
- force the value of options dropdown list to  be `[]` while lqas/im data is still fetching to prevent drawing the map before colors are available
=> POLIO-187 fix map bug

hat/assets/js/apps/Iaso/domains/app/translations/en.json, hat/assets/js/apps/Iaso/domains/app/translations/fr.json, hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js, hat/assets/js/apps/Iaso/domains/instances/components/UserOrgUnitRestriction.js, hat/assets/js/apps/Iaso/domains/instances/messages.js, hat/assets/js/apps/Iaso/utils/usersUtils.js, iaso/api/instances.py, iaso/tests/api/test_instances.py
Follow up on IA-987 pr, This a proposal according to Martin suggestion to display a warning to the user when the org unit he can see are restricted.
Wholly open to suggestions  on how we can make it look nicer and how to improve the warning  and for a French translation. We can also replicate this in the OrgUnit page
=> IA-1007 Display warning for restricted user

hat/assets/js/apps/Iaso/domains/forms/components/FormsFilterComponent.js, plugins/polio/api.py
Add "skipped_forms": skipped_forms to the response which contains a count , skipped form id, round and date.
Add count of invalid rounds and unknown rounds.
Remove auto assign Rdn0 to Rnd1.
=> IA-1027 Add skipped forms to LQASStats response

iaso/api/export_requests.py, iaso/api/forms.py, iaso/dhis2/datavalue_exporter.py
As a temporary fix for the Uganda export that were staying as queued, I implemented a timeout, that happen when creating new export requests. This is a temporary fix till we move it to the task worker system.
I also put a mitigation for when the system was craching because of queued ExportRequest with no attached status, and thus nos attached submission, but I still haven't figured how theses happened in the first place, since normally the system forbidding creating those. Theses requests were created by the properly it seems so there is probably a serious bug underneath that may cause problem for the user. From the sentry log it's not a recent problem either. So with the fix it now display a proper error message  but the error is still occuring
=> IA-1028 & IA-1025 failing export
