BLSQ/iaso

hat/webpack.dev.js
hat/webpack.prod.js
package-lock.json
package.json

Update to webpack 5

---

hat/assets/js/apps/Iaso/constants/menu.js
hat/assets/js/apps/Iaso/constants/routes.js
hat/assets/js/apps/Iaso/domains/app/components/MenuItemComponent.js
hat/assets/js/apps/Iaso/domains/app/components/SidebarMenuComponent.js
hat/assets/js/apps/Iaso/domains/users/utils.js

- fix one permission label error
- check permissions for all submenu, not only first two levels

IA-437: Permissions check

---

iaso/api/dhis2_ou_importer.py
iaso/management/commands/dhis2_ou_importer.py
iaso/tasks/dhis2_ou_importer.py
iaso/urls.py

Import is available here: /api/dhis2ouimporter/
- source id is required (not possible to create a source by name)
- version number is not required and will be created if not existing
- import of org unit types is not working for now

IA-440 dhis2 ou importer api

---

hat/assets/js/apps/Iaso/constants/filters.js
hat/assets/js/apps/Iaso/constants/routes.js
hat/assets/js/apps/Iaso/domains/forms/index.js
iaso/api/forms.py

IA-445 Allow to search forms in the dashboard

---

hat/assets/js/apps/Iaso/components/tables/SingleTable.js
hat/assets/js/apps/Iaso/domains/instances/index.js
hat/assets/js/apps/Iaso/domains/instances/index.spec.js
hat/assets/js/apps/Iaso/utils/mapUtils.js
hat/assets/js/apps/Iaso/utils/tableUtils.js

- Don't load all instances until the map is displayed on the list of instances.
- remove shadow png missing
- fix a search instances issue

IA-454 instances load

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitForm.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitInfosComponent.js
iaso/api/org_units.py

IA-472: allow to change source ref on org unit

---

README.rst
iaso/management/commands/create_and_import_data.py

This is the very first step of automating the onboarding process for new developers. More to come...

Automate create and import data

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitMapComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitTypeChipsFilterComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/details.js
hat/assets/js/apps/Iaso/domains/orgUnits/reducer.js
hat/assets/js/apps/Iaso/domains/orgUnits/utils.js
hat/assets/js/apps/Iaso/utils/mapUtils.js

Use marker cluster only if two markers are on the same coordinates.
https://user-images.githubusercontent.com/12494624/114521337-9bc3b100-9c42-11eb-96b2-e8725e3d90b7.mp4
A simple way to have two markers on the same coordinates is to import a second time schools.csv on another source (cf README)

IA-96: orgunit detail cluster

---

iaso/api/org_units.py

- Adding the groups in the excel file when exporting org unit
---
Screenshot of the exported file. In this test, `Kaio's Group and Group 3` are from sourceVersion 1 while `Group 4` is from sourceVersion 2
PS: Branched from #101

[IA-465] Adding the groups in the excel file when exporting orgunit

---

plugins/polio/js/package-lock.json
plugins/polio/js/package.json
plugins/polio/js/src/components/Dashboard.js
plugins/polio/js/src/hooks/useCampaign.jsx
plugins/polio/js/src/index.js
plugins/polio/js/src/utils/networking.js

- (internal) Networking layer setup
-  List campaigns

List campaigns

---

plugins/polio/serializers.py

- Missing create method for the serializer
- Not being able to create a campaign with the related round models

Fix not being able to create a campaign

---

plugins/polio/serializers.py

- Method put/patch for campaign and related round models

Add updating campaign model with related models functionality

---

plugins/polio/js/src/components/Dashboard.js

- removed dummy data and use `xx`

[POLIO] Copy changes

---

plugins/polio/js/package-lock.json
plugins/polio/js/package.json

- lodash.merge as a dependency in package.json

[POLIO] Add lodash.merge dependency

---

hat/menupermissions/models.py
iaso/api/setup_account.py
iaso/tests/api/test_setup_account.py
iaso/urls.py

allow creating the account, datasource and user in one go

API to create new account IA-522

---

iaso/gpkg/export.py

otherwhise it was left empty and could not display properly in qgis

IA-567 Include the projection info in geopackage

---

hat/assets/js/apps/Iaso/styles/map.js
hat/assets/js/apps/Iaso/utils/mapUtils.js

allow secondary color for cluster

---

plugins/polio/js/src/components/Dashboard.js

- Vials calculation
- Cost per child calculation (added some logic to prevent divide by zero or wrong results, only when a round has a population and a cost, it's added to the calculation)
- Title
- Sync inputs to detection form
- Missing inputs on round 2 step

[IA-547] WHO feedback

---

hat/assets/js/apps/Iaso/domains/instances/config.js

there is one instance without org unit...
https://iaso-staging.bluesquare.org/dashboard/instances/formId/6/page/1/withLocation/true/columns/updated_at,org_unit__name,created_at,status

IA-585: Instances list was crashing  on a specific form

---

plugins/polio/js/src/components/Dashboard.js

- some simple before/after date validation via Yup

[IA-576] Date validation (before / after)

---

hat/settings.py
iaso/tests/api/test_forms.py
iaso/tests/api/test_instances.py
iaso/tests/api/test_orgunits.py
requirements.txt

- Django rest framework csv renderer
---
Closes https://bluesquare.atlassian.net/browse/IA-575

Add django rest framework csv renderer

---

beanstalk_worker/__init__.py

and make them appear in the logs

Log task exception to sentry

---

plugins/polio/js/.env.local

- Build for plugin polio locally, by adding the needed default values

Set proper defaults for local setup of plugin polio

---

iaso/gpkg/export_gpkg.py
iaso/tests/gpkg/test_export2.py

we had a strange bug when all the orgunit we exported had no parents the export would fail

Fix pandas edge case

---

hat/settings.py

Fix comment customization

---

hat/assets/js/apps/Iaso/components/logs/LogCompareComponent.js
hat/assets/js/apps/Iaso/components/logs/LogsComponent.js
iaso/api/logs.py

Fix https://bluesquare.atlassian.net/browse/IA-306 
also fix modification date not showing properly

Ia 306 bulk update show history

---

iaso/tests/test_dhis2_ou_importer.py

Test the Dhis2_ou_importer task

---

iaso/api/org_units.py
iaso/gpkg/export_gpkg.py

Disable optimisation when doing multi search export. This should be better fixed since it will render thing quite slow

IA-642 Temporary fix for multi search export

---

iaso/models/org_unit.py
plugins/polio/serializers.py
requirements.txt

- Use django-ltree to get org unit ancestors 
- Add Org unit serializer to CampaignSerializer

Get Org Unit root using ltree

---

hat/assets/js/apps/Iaso/components/maps/GeoJsonMapComponent.js
hat/assets/js/apps/Iaso/components/maps/MarkerMapComponent.js
hat/assets/js/apps/Iaso/components/maps/PolygonMapComponent.js
hat/assets/js/apps/Iaso/domains/instances/components/InstancesMapComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgunitsMapComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/OrgUnitMapComponent.js

added it to all the map I found

IA-405 Maps: add scale bar

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsFiltersComponent.js

Typing " in the search box results in a blank page (and errors in chrome webtools)

IA-623: avoid crash while searching  " 

---

hat/assets/js/apps/Iaso/domains/dataSources/components/ImportGeoPkgDialog.js
hat/assets/js/apps/Iaso/domains/dataSources/config.js
package-lock.json

- restrict dropdown options to projects linked to datasource in `ImportGeoPkg`
https://user-images.githubusercontent.com/38907762/123818220-170b3980-d8f9-11eb-9d2e-18a22708d98c.mov

IA645 feat only show existing projects in dropdown

---

hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js

https://user-images.githubusercontent.com/82500/123826633-3ce80c80-d900-11eb-82c1-48e13581fb84.mp4

IA-646 Mark Version as mandatory when making source default

---

scripts/eb_deploy.py

this should fix the issue when we try to fetch ressource for terminated Env

Make eb_deploy.py  ignore env that are not ready

---

plugins/polio/js/src/components/Dashboard.js
plugins/polio/js/src/hooks/useGetCampaigns.js
plugins/polio/js/src/styles/theme.js

- Allow to download the campaign data as csv

[IA-605]  Allow to download the campaign data as csv

---

hat/assets/js/apps/Iaso/domains/dataSources/components/ImportGeoPkgDialog.js
package-lock.json

- Fixed bug with `versionNumber` value
https://user-images.githubusercontent.com/38907762/124145731-57032580-da8d-11eb-899a-8fb1273bc9aa.mov

fix: ImportGeoPckg reliably sends request

---

hat/assets/js/apps/Iaso/components/maps/markers/CircleMarkerComponent.js
hat/assets/js/apps/Iaso/components/maps/markers/MarkerComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/EditableGoup.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/MarkerInputs.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/OrgUnitMapComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/details.js
iaso/api/org_units.py

since we now have it in frontend

remove old hack for alitude in api

---

hat/assets/js/apps/Iaso/components/filters/DatesRange.js
hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
hat/assets/js/apps/Iaso/domains/instances/index.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsFiltersComponent.js
hat/assets/js/apps/Iaso/domains/users/components/ProtectedRoute.js

IA-670: use outlined variant for date range

---

hat/assets/css/_languagePicker.scss
hat/assets/css/_login.scss
hat/assets/css/index.scss
hat/assets/js/apps/Iaso/domains/app/actions.js
hat/assets/js/apps/Iaso/domains/app/reducer.js
hat/assets/js/apps/Iaso/domains/users/components/ProtectedRoute.js
hat/assets/js/apps/Iaso/domains/users/components/ProtectedRoute.spec.js
hat/assets/js/apps/Iaso/utils/cookies.js
hat/assets/js/test/dom.js
hat/settings.py
hat/templates/iaso/base.html
hat/templates/iaso/forgot_password.html
hat/templates/iaso/forgot_password_confirmation.html
hat/templates/iaso/language_picker.html
hat/templates/iaso/login.html
hat/urls.py

IA-582 login language selector

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/AddOrgUnitComment.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitForm.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitLevelFilterComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/details.js

- Removed null errors
- Refactored `/orgUnits/details.js` to prevent `setState` to be fired before end of async code execution in `componentDidUpdate`
- removed some dead code
https://user-images.githubusercontent.com/38907762/124924674-faa78500-dffb-11eb-88eb-6a3139542b12.mov

IA 672 org unit children page is blank

---

hat/assets/js/apps/Iaso/components/files/VideoItemComponent.js
hat/assets/js/apps/Iaso/components/filters/DatesRange.js
hat/assets/js/apps/Iaso/components/logs/LogCompareComponent.js
hat/assets/js/apps/Iaso/domains/app/components/LanguageSwitchComponent.js
hat/assets/js/apps/Iaso/domains/forms/config.js
hat/assets/js/apps/Iaso/domains/forms/configArchived.js
hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsExportRequests.js
hat/assets/js/apps/Iaso/domains/instances/components/InstancePopoverComponent.js
hat/assets/js/apps/Iaso/domains/instances/index.js
hat/assets/js/apps/Iaso/domains/links/components/LinksValueComponent.js
hat/assets/js/apps/Iaso/domains/links/config.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitInfosComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitPopupComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/config.js
hat/assets/js/apps/Iaso/domains/orgUnits/index.js
hat/assets/js/apps/Iaso/domains/periods/components/DatePickerComponent.js
hat/assets/js/apps/Iaso/domains/users/components/ProtectedRoute.js
hat/assets/js/apps/Iaso/utils/dates.js

Change date format everywhere in the app using language selected.

IA-684: Date format

---

plugins/polio/migrations/0020_fix_statuses.py

possible Status were changed but were still present and DB which prevented the user modifying the object

Migrate old invalid status to FIX POLIO-62

---

docker-compose.yml
plugins/polio/api.py
plugins/polio/models.py
plugins/polio/preparedness/client.py
plugins/polio/preparedness/conditional_formatting.py
plugins/polio/preparedness/parser.py
plugins/polio/preparedness/spreadsheet_manager.py
plugins/polio/serializers.py
plugins/polio/tests.py
plugins/test/admin.py
plugins/test/api.py
requirements.txt

The code is from Kaio #273 but it had a lot of unrelated change due to automated formatting which made it harder to  compare or merge,  so I remade a "clean" commit from his code.

[IA-666] Add an api to generate a google sheets out of the list of districts of a campaign

---

plugins/polio/js/src/components/MapComponent/Context.js
plugins/polio/js/src/components/MapComponent/MapComponent.jsx

not the most efficient because we re convert the geojson in shape but should do for now

IA-611 Correctly zoom on all the shape

---

plugins/polio/js/src/components/Dashboard.js

When a district is selected while creating a new campaign, its color will be red.
https://user-images.githubusercontent.com/47039931/126795361-e82c396b-2749-49a7-b9de-81f441472856.mov

IA-663: Set different color for initial district

---

plugins/polio/preparedness/spreadsheet_manager.py
plugins/polio/serializers.py

- Update template mapping data
---
Link of the new template: https://docs.google.com/spreadsheets/d/1DrA0NCO9h-EjvQ-RobZJjwiB0qPCwd5P8IC1uMkeMoA/edit#gid=1841555907

Update template mapping

---

plugins/polio/js/src/forms/PreparednessForm.js

add a bit of padding to be more readable

quickfix for ui polio

---

hat/assets/js/.eslintrc.json

https://www.npmjs.com/package/eslint-plugin-react-hooks#installation

Activate eslint rule for react hooks

---

hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsField.js

IA-639 Improve the display of export errors on iaso

Allowing errors to wrap for DHIS2 exports

---

beanstalk_worker/urls.py
hat/dashboard/urls.py
hat/sync/urls.py
hat/urls.py
iaso/urls.py
plugins/polio/urls.py

don't impact much it's mostly to stay up to date on best practice
but it should prevent future regression on the password reset

Django use new path() syntax for routing instead of url()

---

plugins/polio/js/src/components/MapComponent/MapComponent.jsx

opening in draft since it's only district and not region

IA-712 add popup with orgunit name

---

plugins/polio/js/src/components/Dashboard.js
plugins/polio/js/src/styles/theme.js

it's not the prettiest but it works

IA-715 list of districts in scope map

---

.ebextensions/70_crontab.config
hat/settings.py
plugins/polio/management/commands/refresh_preparedness_data.py
scripts/command_in_eb.sh

add a cron to sync preparedness data

IA-588 auto sync the preparedness data

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgunitsMapComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/index.js

- Org Units list's map doesn't crash anymore on reload, or when using deep linking
If approved, pls Squash & Merge

Ia 725 map crash

---

package-lock.json
plugins/polio/js/src/components/Dashboard.js
plugins/polio/js/src/components/MapComponent/MapComponent.js
plugins/polio/js/src/constants/messages.js
plugins/polio/js/src/hooks/useGetGeoJson.js
plugins/polio/js/src/styles/theme.js

- Display Region boundaries on Scope map
- Add "Region" Column in Scope
- Table columns have a max width and will crop text on overflow. A tooltip display's the full name on hover
- Enable Region deselection from Scope table
- Added region to map tootltip (not shown on video)
- Replaced `useGetRegionGeoJson` with `useGeoJson`, which can take 'DISTRICT' or 'REGION' as parameter
- Refactored `ScopeForm`'s `onSelectOrgUnit` for clarity
- Used separate `Pane`s in `MapComponent` to display districts and regions
https://user-images.githubusercontent.com/38907762/130103098-f550d083-8e09-4c54-adfa-a74544671bc7.mov

IA-664 polio display provinces

---

hat/assets/js/apps/Iaso/domains/dataSources/components/AddTaskComponent.js
hat/assets/js/apps/Iaso/domains/dataSources/components/AddTaskComponent.spec.js
hat/assets/js/apps/Iaso/domains/dataSources/requests.js
hat/assets/js/test/utils.js

SetUp testing framework so we can task component with react-query

AddTask port to react query and setup test

---

hat/assets/js/apps/Iaso/libs/Api.js
hat/assets/js/apps/Iaso/utils/requests.spec.js
hat/assets/js/test/helpers.js
hat/assets/js/test/utils/requests.js
package-lock.json
package.json

don't remove superagent dependency yet because there are unused code that use it... And I removed that code in PR #326 
Added node-fetch as a dependency for testing.
Note that we had a bunch of code using Fetch already in Stephan's PBF code, and since it  was not present when testing it was either silently failing or not tested.

Replace superagent by fetch in front

---

hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js

even though it was
and it was marked as clerable but the button did nothing.

In datasource dialog, Projects was not marked as required

---

hat/assets/js/apps/Iaso/domains/instances/components/CreateReAssignDialogComponent.js
hat/assets/js/apps/Iaso/domains/instances/index.js

- removed condition blocking rendering of button
- fixed typo that prevented `PeriodPicker`'s dropdown list to be populated when period exists
https://user-images.githubusercontent.com/38907762/133250340-19f651d7-03b0-4eb2-8e14-137dc8b10560.mov

IA-774 patch restore button, patch empty picker

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewPicker.js
plugins/polio/js/src/components/Dashboard.js
plugins/polio/js/src/components/Inputs/OrgUnitsSelect.js
plugins/polio/js/src/hooks/useGetOrgUnits.js

https://user-images.githubusercontent.com/82500/133407045-9b4afe3b-81b6-48d9-8b39-3c75f8126b13.mp4

IA786 Polio: replace custom OrgUnit selector by TreeView

---

iaso/models/org_unit.py
plugins/polio/js/src/components/CountryNotificationsConfig/Table/CountryNotificationsConfigTable.js
plugins/polio/js/src/components/Dashboard.js
plugins/polio/js/src/forms/PreparednessForm.js
plugins/polio/js/src/hooks/useGetPreparednessData.js
plugins/polio/js/src/hooks/useSaveCampaign.js
plugins/polio/js/src/utils/networking.js

Fix error handling in polio, properly display Snackbar on modification  and bind the error from the server to the main Formik instance.
also fix a few visual bug.
https://user-images.githubusercontent.com/82500/133409431-46136eb8-3c50-49cc-b0f9-a1a1e542e3f8.mp4

IA-694 polio proper api error  handling

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsMultiActionsDialog.js

not working when filtering on parent orgunit and selecting ALL orgunits

IA-776 fix Bulk update of OrgUnit

---

hat/assets/js/apps/Iaso/domains/app/translations/en.json
hat/assets/js/apps/Iaso/domains/completeness/components/CompletenessPeriodComponent.js
hat/assets/js/apps/Iaso/domains/completeness/messages.js

- fixed the translation error for derived instances
- removed unused imports
- removed variable naming conflict

IA-286 fix translation error, ambiguous var naming

---

hat/settings.py
plugins/polio/api.py

and sorting by vaccine.
not yet the sort/filter by country

IA-804 allow filtering on orgunit campaign

---

hat/assets/js/apps/Iaso/index.js
hat/assets/js/apps/Iaso/routing/hooks.js
hat/dashboard/urls.py
hat/dashboard/views.py
iaso/api/org_units.py
plugins/polio/api.py
plugins/polio/js/config.js
plugins/polio/js/src/components/MapComponent/CalendarMap.js
plugins/polio/js/src/components/campaignCalendar/constants.js
plugins/polio/js/src/components/campaignCalendar/index.js
plugins/polio/js/src/components/campaignCalendar/popper/R1.js
plugins/polio/js/src/pages/Calendar.js
plugins/polio/serializers.py

Embbedable CalendarMap page. Changed the campaign Api to work for anonymous users. Modifier the react router usage and the django router so we could have anonymous page. Used it in for a new page. I made it so we could reuse the CalendarMap page as-is and not have to a copy. 
The menu is removed in the embedded page, the edit button in the popup is removed as well.
I changed a bit how the next and previous buttons works. Constructed the url from the router so it doesn't matter whether we are on the embedded url or not;  and replaced button with Link, the last modification is not  strictly necessary, but I find it nice, it show the url in advance and allow opening in tabs.

POLIO-99 Embeddable calendar

---

plugins/polio/js/src/components/campaignCalendar/Nav.js
plugins/polio/js/src/components/campaignCalendar/map/CalendarMap.js

this make use of the cache so it doesn't reload the same shape every time
and it display the shape as soon as it has some instead of waiting for all of them

Port CalendarMap top react-query

---

plugins/polio/js/src/components/CreateEditDialog.js

- Add an indicator when tabs overflow available space
https://user-images.githubusercontent.com/38907762/136013081-f6880078-aef5-4af3-ac37-777b46b9208e.mov

POLIO-103: make tabs scrollable

---

iaso/migrations/0108_add_page_feature_flag_20211005_1346.py

was a bit annoyed to always have to add it manually when testing.

Data migration to add the Page account feature flags

---

hat/assets/js/apps/Iaso/components/forms/ColorPicker.js

IA-826: hide color input

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgunitsMapComponent.js

- change markers z- index 
-  fix clustering switch

ORGUNITS MAP z-index

---

plugins/polio/js/src/components/Dashboard.js
plugins/polio/js/src/constants/messages.js
plugins/polio/js/src/constants/translations/en.json
plugins/polio/js/src/constants/translations/fr.json
plugins/polio/models.py
plugins/polio/serializers.py

- Modified models.py and serializers.py so the back end sends a translation key
- Modified Dashboard.js so it formats the key received from backend
- Added messages
- Added translations

POLIO-102: translate campaign statuses

---

beanstalk_worker/__init__.py
iaso/tasks/dhis2_ou_exporter.py

even if they forgot to mark it themselves

Ensure that task are always marked as done after completion

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/OrgUnitMapComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/utils.js

https://user-images.githubusercontent.com/38907762/140084057-02898aca-b91e-442e-941a-d1dae68a083e.mov

IA-888 patch getMarkersList

---

hat/assets/js/apps/Iaso/domains/instances/index.spec.js

Skip test that takes 15 min to end

IA-866: skip lagging test

---

hat/assets/js/apps/Iaso/domains/instances/config.js
hat/assets/js/apps/Iaso/domains/instances/constants.js

https://user-images.githubusercontent.com/82500/140540314-a516a989-0cd4-4863-81b4-d312f6cd8806.mp4

Multi form : add link to form

---

hat/assets/js/apps/Iaso/domains/dataSources/requests.js
hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
hat/assets/js/apps/Iaso/hooks/form.js

Checkbox and textual search were broken
Value couldn't be reset

Multi form fix filter

---

hat/assets/js/apps/Iaso/domains/instances/index.js

We checked the length of the string and not the list

Fix Create button didn't reliably appear in Submission page

---

hat/assets/js/apps/Iaso/domains/dataSources/components/VersionsDialog.js
iaso/api/source_versions.py
iaso/models/base.py

VersionDialog add orgunit counts

---

hat/assets/js/apps/Iaso/styles/mapCluster.js
hat/assets/js/apps/Iaso/utils/mapUtils.js
hat/assets/js/apps/Iaso/utils/requests.js

Ia 908 ia 905 comments & cluster icon

---

hat/assets/js/apps/Iaso/domains/completeness/components/CompletenessPeriodComponent.js
hat/assets/js/apps/Iaso/domains/completeness/config.js
hat/assets/js/apps/Iaso/domains/instances/details.js
hat/assets/js/apps/Iaso/routing/redirections.js
iaso/api/enketo.py

Fix a few of the issues that were caused by the url renaming:
- Wrong url after file creation (url is encoded in api)
- Link in preparedness to submission broken
- Back button from submission broken (when you came directly from a link)
- Added a Redirection which should resolve the other problem that may arise

IA-911 Fix links problem in multi form

---

hat/assets/js/apps/Iaso/domains/forms/components/OrgUnitTypeFilterComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/OrgUnitMapComponent.js

+ ou map detail marker depth fix

IA-903 orgunit detail map crash

---

hat/assets/js/apps/Iaso/domains/orgUnits/messages.js

IA-897 patch tooltip icon message

---

iaso/api/instances.py

Form with MultiLang label were making the excel lib crash

IA-893 Excel Export of Multilang form submission

---

docker-compose.yml
hat/settings.py
hat/urls.py
iaso/migrations/0110_make_readonlyrole.py
iaso/views.py
plugins/polio/migrations/0034_make_readonlyrole.py
requirements.txt
runiasodev.sh

you can go to /explore to see it in action
New python deps you will need to rebuild your docker iaso container: docker-compose build iaso.
On the deployment side we will need to create a new user for each env/db and configure it.
https://user-images.githubusercontent.com/82500/140764755-c9ecff5f-8f31-495f-9375-b3a588b51d64.mp4

IA-896 Integrate django-sql-dashboard

---

hat/assets/js/apps/Iaso/domains/users/components/PermissionsSwitches.js

IA-917: sort user perms

---

hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.js

- store "levels" param in state and use value as `initialSelection` prop in treeview
- update state value on search
Uploading Screen Recording 2021-11-17 at 16.39.14.mov…

IA-922 preserve treeview selection when navigation back to submissions

---

plugins/polio/js/src/components/campaignCalendar/cells/CampaignDuration.js
plugins/polio/js/src/components/campaignCalendar/popper/R1.js
plugins/polio/js/src/components/campaignCalendar/utils.js
plugins/polio/js/src/constants/messages.js
plugins/polio/js/src/constants/translations/en.json
plugins/polio/js/src/constants/translations/fr.json

POLIO-120: remove campaign duration if is preventive

---

hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/DynamicSelect.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/TreeViewResultsCountSelect.js
hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.js
package-lock.json

- removed uses of `iasoGetRequest`
- updated network code to use `react-query`& `useSnackQuery`
- refactored `DynamicSelect` to use same component as `Table` to select amount of results to display
- updated dep to blsq-comp
https://user-images.githubusercontent.com/38907762/141144341-ccc2839c-b2fb-4372-8ed1-ba5c8228018a.mov

IA-877 use snack query in treeview

---

hat/assets/js/apps/Iaso/constants/menu.js
hat/assets/js/apps/Iaso/domains/forms/config.js
hat/assets/js/apps/Iaso/domains/instances/components/InstancesTopBar.js
hat/assets/js/apps/Iaso/domains/instances/constants.js

display form column if more than one form

---

plugins/polio/js/src/components/campaignCalendar/map/CalendarMap.js

- Added a `useQueries` series of requests go get regions for each campaign and used that data to display region name in tooltip

Polio 128 add region to tooltip

---

hat/assets/js/apps/Iaso/domains/completeness/components/CompletenessPeriodComponent.js
hat/assets/js/apps/Iaso/domains/completeness/config.js

- Fixed link in config
https://user-images.githubusercontent.com/38907762/145029783-ec02b748-025f-4692-b03d-8a5ada0ab1f2.mov

IA-960 fix link url to submissions

---

hat/assets/js/apps/Iaso/domains/app/translations/en.json
hat/assets/js/apps/Iaso/domains/app/translations/fr.json
hat/assets/js/apps/Iaso/domains/dataSources/requests.js
hat/assets/js/apps/Iaso/utils/requests.js
hat/assets/js/apps/Iaso/utils/requests.spec.js

- refactored `fetchAlgorithmRuns`
- replaced `useQuery`with `useSnackQuery` in datasources' `requests.js`

IA-952 remove iasoGetRequest

---

plugins/polio/js/src/forms/ScopeForm.js

- made `groups`variable null safe

POLIO-132: fix null error crash

---

plugins/polio/js/src/components/LQAS-IM/LqasImTable.js
plugins/polio/js/src/pages/IM/ImMap.js
plugins/polio/js/src/pages/IM/constants.js
plugins/polio/js/src/pages/IM/imTableConfig.js
plugins/polio/js/src/pages/IM/index.js
plugins/polio/js/src/pages/LQAS/LqasMap.js
plugins/polio/js/src/pages/LQAS/constants.js
plugins/polio/js/src/pages/LQAS/index.js
plugins/polio/js/src/pages/LQAS/lqasTableConfig.js

- orange is now yellow, per client request
- "debug" information is at the bottom of page

POLIO-137 change color, move data

---

plugins/polio/README.md
plugins/polio/preparedness/client.py
plugins/polio/preparedness/parser.py
plugins/polio/preparedness/spreadsheet_manager.py
plugins/polio/serializers.py
plugins/polio/tests.py

Redo the generation of the spreadsheet by changing the way we approach it, we use template cell that we copy.
Accordingly, lot of work is done in the template themselves (ask me for the links).
Fix the missing Security segment  and summary POLIO-117 (and properly parse them)
Fix a lot of display issue and typo
Fix the Graph  at the end of the page (one in national, the other two on issue page)
Fix Date cell being generated accordingly (they now properly popup a calender in the district columns like they did for the regions)
Fix all the conditional formatting
Do less query to google so it's speed up the generation
Simplify the code a lot
This pr is based on PR #522 so we can configure the access via the DB and use the versionning of templates

Polio 117 fix preparedness generation

---

hat/assets/js/apps/Iaso/domains/dataSources/components/ImportGeoPkgDialog.js

version_number was not send when equal 0

IA-973 ImportGPKG Fix updating version number 0

---

hat/assets/js/apps/Iaso/domains/forms/config.js
hat/assets/js/apps/Iaso/domains/forms/config.spec.js
hat/assets/js/apps/Iaso/domains/orgUnits/details.js

IA-951: Org unit detail link to submissions

---

iaso/admin.py
iaso/models/base.py

various improvement to the django admin  for Org Unit Group and instance that I had locally

Django admin improvement

---

hat/assets/js/apps/Iaso/domains/dataSources/components/ExportToDHIS2Dialog.js
hat/assets/js/apps/Iaso/domains/dataSources/requests.js

see bug description. Allow reducing number of org unit considered that was causing a OOM by allowing to set the type and status on the ref source too

IA-996 DHIS2  Export crash, allow selecting org unit type and status

---

hat/assets/js/apps/Iaso/domains/orgUnits/index.js

- catch the error that was causing the freeze

IA-677 catch error

---

plugins/polio/api.py
plugins/polio/js/src/components/LQAS-IM/LqasImPercentageChart.tsx
plugins/polio/js/src/components/LQAS-IM/NoFingerMark.tsx
plugins/polio/js/src/components/LQAS-IM/PercentageChartWithTitle.tsx
plugins/polio/js/src/constants/types.ts
plugins/polio/js/src/pages/IM/constants.ts
plugins/polio/js/src/pages/IM/utils.ts
plugins/polio/js/src/pages/LQAS/utils.ts
plugins/polio/js/src/utils/index.js

- Fix the ordering of `PercentageBarChart` in Chrome
- Order Bars for "Reasons no vaccination"
- Convert "Reasons no vaccination" numbers to percentages
- Change the colors tresholds for the LQAS `PercentageBarChart`
- LQAS: filter out "Reasons no finger mark" for disqualified districts

POLIO-155, POLIO-158, POLIO-161, POLIO-162: LQAS/IM improvements, batch 1

---

plugins/polio/api.py
plugins/polio/preparedness/parser.py

use the round number in the spreadsheet
temporary fix till we allow setting a spreadsheet per round

:fire: Fix detection of date for preparedness history

---

plugins/polio/js/src/components/LQAS-IM/ImSummary.tsx
plugins/polio/js/src/components/LQAS-IM/LqasImMap.js
plugins/polio/js/src/components/LQAS-IM/LqasSummary.tsx
plugins/polio/js/src/constants/translations/fr.json
plugins/polio/js/src/pages/IM/index.js
plugins/polio/js/src/pages/LQAS/index.js
plugins/polio/js/src/pages/LQAS/utils.ts

- Added LqasSummary and ImSummary to display "key" data
- Applied the same color conventions as those requested for the graphs
There's duplicated styling code. If it's OK for you I'd rather refactor it after we've shown the changes to the client on Monday.

Polio 156 polio 160 add key fields

---

plugins/polio/api.py
plugins/polio/js/src/components/LQAS-IM/CaregiversTable.tsx
plugins/polio/js/src/constants/messages.js
plugins/polio/js/src/constants/translations/en.json
plugins/polio/js/src/constants/translations/fr.json
plugins/polio/js/src/pages/IM/constants.ts
plugins/polio/js/src/utils/index.js

- Reduce column size to 4 as per https://bluesquare.atlassian.net/browse/POLIO-159?atlOrigin=eyJpIjoiMjU3MzA3OTZjZDcxNDdkZDg0MjUzOWRlMGM5NTE0NjciLCJwIjoiaiJ9 requirements
- modify api to send % caregivers informed, best info source(s) and rate of caregivers using that source
- delete obsolete list in `constants`

Polio 159 update caregivers table

---

plugins/polio/js/src/components/HorizontalDivider.tsx
plugins/polio/js/src/components/LQAS-IM/CaregiversTableHeader.tsx
plugins/polio/js/src/components/LQAS-IM/GraphTitle.tsx
plugins/polio/js/src/components/LQAS-IM/ImSummary.tsx
plugins/polio/js/src/components/LQAS-IM/LqasImMapHeader.tsx
plugins/polio/js/src/components/LQAS-IM/LqasImPercentageChart.tsx
plugins/polio/js/src/components/LQAS-IM/LqasSummary.tsx
plugins/polio/js/src/components/LQAS-IM/NoFingerMark.tsx
plugins/polio/js/src/components/LQAS-IM/PercentageChartWithTitle.tsx
plugins/polio/js/src/pages/IM/index.js
plugins/polio/js/src/pages/IM/utils.ts
plugins/polio/js/src/pages/LQAS/index.js
plugins/polio/js/src/pages/LQAS/utils.ts
plugins/polio/js/src/utils/index.js

- fix some null errors
- add horizontal divider
- cosmetic fixes
- fix IM global crash

Lqas im fine tuning

---

hat/webpack.dev.js

WEBPACK and .map.js

---

iaso/api/pages.py

@olethanh I don't filter on account otherwise the previous Pages created without account wont be displayed

fix duplicates

---

plugins/polio/api.py
plugins/polio/js/src/components/LQAS-IM/DatesIgnored.tsx
plugins/polio/js/src/components/LQAS-IM/DistrictsNotFound.tsx
plugins/polio/js/src/components/LQAS-IM/LqasImPercentageChart.tsx
plugins/polio/js/src/components/LQAS-IM/NoDataForBarChart.tsx
plugins/polio/js/src/pages/IM/requests.js
plugins/polio/js/src/pages/LQAS/index.js
plugins/polio/js/src/utils/LqasIm.tsx
plugins/polio/js/src/utils/index.js

⚠️ Branch already merged https://github.com/BLSQ/iaso/pull/596
- add default values to several utils to avoid crash on null value

Polio 178 null error lqas im

---

hat/assets/js/apps/Iaso/components/filters/DatesRange.js
hat/assets/js/apps/Iaso/utils/dates.ts
plugins/polio/js/src/components/campaignCalendar/Filters.js

POIO-179: Type a date not working

---

plugins/polio/js/src/components/LQAS-IM/NoFingerMark.tsx
plugins/polio/js/src/components/PercentageBarChart/utils.js

POLIO-172: create custom label for horizontal bar chart

---

plugins/polio/js/src/pages/IM/index.js
plugins/polio/js/src/pages/LQAS/index.js

Polio 173 country select

---

hat/assets/js/apps/Iaso/domains/instances/components/InstancesTopBar.js
hat/assets/js/apps/Iaso/domains/instances/index.js

IA-1020: Missing label keys column

---

hat/assets/js/apps/Iaso/domains/periods/components/PeriodPicker.js
hat/assets/js/apps/Iaso/domains/periods/utils.js
hat/assets/js/apps/Iaso/utils/featureFlags.js
iaso/migrations/0113_add_account_feature_flag_quarter.py

- display + hide Quarter label behind feature flag
- create migration

IA-833 : display + hide Quarter label behind feature flag

---

plugins/polio/api.py
plugins/polio/tests/test_base.py

and modify the parameter's name
and make "all" filter works as documented

IA-1021 Polio campaign return undeleted per default

---

plugins/polio/js/src/components/LQAS-IM/LqasImMap.js
plugins/polio/js/src/hooks/useGetCampaigns.js
plugins/polio/js/src/pages/IM/index.js
plugins/polio/js/src/pages/LQAS/index.js
plugins/polio/js/src/utils/LqasIm.tsx

- updated `useGetCampaigns` hook to fetch based on `country` state value
- removed obsolete `findCountryIds` method
- updated loading status props to use `isFetching`for campaigns
- improved `LoadingSpinner`on map
https://user-images.githubusercontent.com/38907762/150979128-4ae27ef1-d0c8-402b-a40f-1b1dc32823a6.mov

POLIO-181 show all campaigns for country in select

---

hat/assets/js/apps/Iaso/domains/completeness/components/CompletenessPeriodComponent.js
hat/assets/js/apps/Iaso/domains/completeness/index.js

IA-833: usePrettyPeriod on completeness

---

iaso/api/instances.py
iaso/tests/api/test_instances.py

User who are limited to certain org unit can only see form submissions for theses region (and region bellow)

IA-978 Limit submissions for restricted user

---

hat/assets/css/_login.scss
plugins/polio/js/config.js
plugins/polio/js/src/components/LQAS-IM/Filters.tsx
plugins/polio/js/src/pages/IM/index.js
plugins/polio/js/src/pages/LQAS/index.js

POLIO-184: Deep link LQAS and IM pages

---

iaso/diffing/dumper.py

Added 
- NA for multipolygons diff 
- NA for New Geoloc Entries w/o comparison
- Empty for entries without any geoloc data

IA-1046 -  Add NA and empty when no geo point

---

plugins/polio/js/src/components/campaignCalendar/Styles.js
plugins/polio/js/src/components/campaignCalendar/map/CalendarMap.js
plugins/polio/js/src/constants/campaignsColors.js
plugins/polio/js/src/constants/virus.js

- hide boundaries if zoom lower than 6
- adapt vaccine legend color with map opacity
- change green vaccine color to red
- hide camaigns legend if not displayed

Boundaries and vaccine color

---

package-lock.json
plugins/polio/js/src/components/LQAS-IM/CaregiversTable.tsx
plugins/polio/js/src/components/LQAS-IM/CaregiversTableHeader.tsx
plugins/polio/js/src/components/LQAS-IM/DatesIgnored.tsx
plugins/polio/js/src/components/LQAS-IM/DistrictsNotFound.tsx
plugins/polio/js/src/components/LQAS-IM/Filters.tsx
plugins/polio/js/src/components/LQAS-IM/GraphTitle.tsx
plugins/polio/js/src/components/LQAS-IM/ImSummary.tsx
plugins/polio/js/src/components/LQAS-IM/LqasImHorizontalChart.tsx
plugins/polio/js/src/components/LQAS-IM/LqasImMap.js
plugins/polio/js/src/components/LQAS-IM/LqasImMapHeader.tsx
plugins/polio/js/src/components/LQAS-IM/LqasSummary.tsx
plugins/polio/js/src/components/LQAS-IM/MapContainer.tsx
plugins/polio/js/src/components/LQAS-IM/NoData.tsx
plugins/polio/js/src/components/LQAS-IM/ScopeAndDNFDisclaimer.tsx
plugins/polio/js/src/hooks/useImData.ts
plugins/polio/js/src/hooks/useLqasData.ts
plugins/polio/js/src/pages/IM/index.js
plugins/polio/js/src/pages/LQAS/index.js

POLIO-201 lqas/im v2

---

iaso/models/base.py
iaso/tests/api/test_instances.py

- https://bluesquare.atlassian.net/browse/IA-964
- [fetch submissions related to org unit in source_ref](https://github.com/BLSQ/iaso/commit/fc8eba9bd6752eb84a15a3140aa936d8302d039d)
- [unit test the search with orgUnit source_ref](https://github.com/BLSQ/iaso/commit/64cf814aebeb33fc4551eebdb8f30e1224eac385)

Ia 964 allow to search submissions by id and ref of the corresponding org units

---

hat/assets/js/apps/Iaso/domains/instances/components/CreateReAssignDialogComponent.js

- hide period picker when form has no periodicity

IA-1026: hide period picker

---

iaso/api/forms.py

Added condition to get queryset to filter on user restricted OU if there is one.

IA114-Filter instance count if user restricted OU

---

iaso/api/org_units.py

:fire: IA-1137 fix broken embedded Campaign map

---

hat/assets/js/apps/Iaso/domains/instances/components/InstancesTopBar.js

only redirect if columns changes

IA-1142: Submissions filters broken
